### ISSUE TITLE
Cannot go back to navigation view

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT301F16T13/ThunderCab#35]
When in profile or requests fragments, you cannot click on navigation in the navigation menu and go back to the navigation menu

**Comment by vitor-vfm** [comment]
That's because the Navigation fragment is not implemented yet. I think this is the part Jesse's working on.

Right now the startNavigationFragment method in NavActivity is empty.

**Comment by JesseFarebro** [comment]
Solved with 52d17f9d6ddc9f08626b6dfb3deb5c850dbca874 and a24964243a0e79b59fab4c0770e0d13972e194fd.

**Comment by cujomalainey** [comment]
This is still broken on master, its the arrow in the top left that is broken, not that actual system back arrow

**Comment by JesseFarebro** [comment]
My bad misread, now fixed with a0fb4671f09b69a85623facd26524371be8f5c5c.
